_pipeline_script: &pipeline_script http://stash.corp.alleninstitute.org/users/jeromel/repos/openscope_dendritic_coupling/raw/pilot_scripts/full_pipeline_script.py?at=640536dc00f226a5c89799cab861c45e43a33fd6
_pipeline_script_md5: &pipeline_script_md5 3202f12edb84ff4f2c7c9f3180b5a10f

### mtrain definitions
name: Openscope_DendriticCoupling_v9

transitions:
  - trigger: progress
    source: PASSIVE_CLUSTER_HAB_10MIN_DAY6
    dest: PASSIVE_CLUSTER_HAB_20MIN_DAY7
    conditions: one_complete

  - trigger: progress
    source: PASSIVE_CLUSTER_HAB_20MIN_DAY7
    dest: PASSIVE_CLUSTER_HAB_30MIN_DAY8
    conditions: one_complete

  - trigger: progress
    source: PASSIVE_CLUSTER_HAB_30MIN_DAY8
    dest: PASSIVE_CLUSTER_HAB_40MIN_DAY9
    conditions: one_complete

  - trigger: progress
    source: PASSIVE_CLUSTER_HAB_40MIN_DAY9
    dest: PASSIVE_CLUSTER_HAB_50MIN_DAY10
    conditions: one_complete

  - trigger: manual
    source: PASSIVE_CLUSTER_HAB_50MIN_DAY10
    dest: PASSIVE_OPHYS_PROD_EXP_DAY11_15

  - trigger: manual
    source: PASSIVE_OPHYS_PROD_EXP_DAY11_15
    dest: PASSIVE_OPHYS_PROD_UNEXP_DAY16_18


stages:
  PASSIVE_CLUSTER_HAB_10MIN_DAY6:
    script: *pipeline_script
    script_md5: *pipeline_script_md5
    parameters:
      stage: PASSIVE_CLUSTER_HAB_10MIN_DAY6
      monitor_name: "Gamma1.Luminance50"
      type: 'hab'
      session_dur: 600
      pre_blank: 30
      post_blank: 30
      inter_blank: 30
      gab_dur:  56
      rot_gab_dur: 56
      sq_dur: 0
      movie_dur: 120 #hab_block length*movie_blocks
      movie_blocks: 1
      gratings_dur: 3 #runs. 1 run = 14.7s so 44.1s
      movie_folder: //allen/programs/mindscope/workgroups/openscope/2022-DendriteCoupling/Scripts/Production/second_version_movies

  PASSIVE_CLUSTER_HAB_20MIN_DAY7:
    script: *pipeline_script
    script_md5: *pipeline_script_md5
    parameters:
      stage: PASSIVE_CLUSTER_HAB_20MIN_DAY7
      monitor_name: "Gamma1.Luminance50"
      type: 'hab'
      session_dur: 1200
      pre_blank: 30
      post_blank: 30
      inter_blank: 30
      gab_dur:  140
      rot_gab_dur: 140
      sq_dur: 0
      movie_dur: 360
      movie_blocks: 3
      gratings_dur: 5 #runs. 1 run = 14.7s so 73.5s
      movie_folder: //allen/programs/mindscope/workgroups/openscope/2022-DendriteCoupling/Scripts/Production/second_version_movies

  PASSIVE_CLUSTER_HAB_30MIN_DAY8:
    script: *pipeline_script
    script_md5: *pipeline_script_md5
    parameters:
      stage: PASSIVE_CLUSTER_HAB_30MIN_DAY8
      monitor_name: "Gamma1.Luminance50"
      type: 'hab'
      session_dur: 1800
      pre_blank: 30
      post_blank: 30
      inter_blank: 30
      gab_dur:  215
      rot_gab_dur: 215
      sq_dur: 0
      movie_dur: 600
      movie_blocks: 5
      gratings_dur: 9 #runs. 1 run = 14.7s so 132.3s
      movie_folder: //allen/programs/mindscope/workgroups/openscope/2022-DendriteCoupling/Scripts/Production/second_version_movies

  PASSIVE_CLUSTER_HAB_40MIN_DAY9:
    script: *pipeline_script
    script_md5: *pipeline_script_md5
    
    parameters:
      stage: PASSIVE_CLUSTER_HAB_40MIN_DAY9
      monitor_name: "Gamma1.Luminance50"
      type: 'hab'
      session_dur: 2400
      pre_blank: 30
      post_blank: 30
      inter_blank: 30
      gab_dur:  250
      rot_gab_dur: 250
      sq_dur: 0
      movie_dur: 960
      movie_blocks: 8
      gratings_dur: 16 #runs. 1 run = 14.7s so 235.2s
      movie_folder: //allen/programs/mindscope/workgroups/openscope/2022-DendriteCoupling/Scripts/Production/second_version_movies

  PASSIVE_CLUSTER_HAB_50MIN_DAY10:
    script: *pipeline_script
    script_md5: *pipeline_script_md5

    parameters:
      stage: PASSIVE_CLUSTER_HAB_50MIN_DAY10
      monitor_name: "Gamma1.Luminance50"
      type: 'hab'
      session_dur: 3000
      pre_blank: 30
      post_blank: 30
      inter_blank: 30
      gab_dur:  360
      rot_gab_dur: 360
      sq_dur: 0
      movie_dur: 1080
      movie_blocks: 9
      gratings_dur: 19 #runs. 1 run = 14.7s so 279.3s
      movie_folder: //allen/programs/mindscope/workgroups/openscope/2022-DendriteCoupling/Scripts/Production/second_version_movies

  PASSIVE_OPHYS_PROD_EXP_DAY11_15:
    script: *pipeline_script
    script_md5: *pipeline_script_md5

    parameters:
      stage: PASSIVE_OPHYS_PROD_EXP_DAY11_15
      monitor_name: "Gamma1.Luminance50"
      type: 'hab'
      session_dur: 3600
      pre_blank: 30
      post_blank: 30
      inter_blank: 30
      gab_dur:  410
      rot_gab_dur: 410
      sq_dur: 0
      movie_dur: 1440
      movie_blocks: 12
      gratings_dur: 21 #runs. 1 run = 14.7s so 308.7s
      movie_folder: //allen/programs/mindscope/workgroups/openscope/2022-DendriteCoupling/Scripts/Production/second_version_movies

  PASSIVE_OPHYS_PROD_UNEXP_DAY16_18:
    script: *pipeline_script
    script_md5: *pipeline_script_md5

    parameters:
      stage: PASSIVE_OPHYS_PROD_UNEXP_DAY16_18
      monitor_name: "Gamma1.Luminance50"
      type: 'ophys'
      session_dur: 4200
      pre_blank: 30
      post_blank: 30
      inter_blank: 30
      gab_dur: 450
      rot_gab_dur: 450
      sq_dur: 0
      movie_dur: 1800
      movie_blocks: 15
      gratings_dur: 26 #runs. 1 run = 14.7s so 382.2s
      movie_folder: //allen/programs/mindscope/workgroups/openscope/2022-DendriteCoupling/Scripts/Production/second_version_movies
